#!/bin/ksh

if [ "${JESDIR}x" = "x" ]
then
	echo "No \$JESDIR, exit"
	return
fi

# Set environment variables
MT_KSH=${PDKSH}; export MT_KSH
MYHOME=${PWD}; export MYHOME
MT_ROOT=${JESDIR}/ejr; export MT_ROOT
# UBBCONFIG=$MYHOME/config/ubbconfig; export UBBCONFIG
MASTER_NAME=SITE1; export MASTER_NAME
TUXCONFIG=$MYHOME/config/tuxconfig; export TUXCONFIG
QMCONFIG=$MYHOME/sysfile/QUE; export QMCONFIG
# LANG=C; export LANG

SPOOL=${MYHOME}/LOGS/sysout; export SPOOL
MT_ACC_FILEPATH=${MYHOME}/acc; export MT_ACC_FILEPATH
MT_LOG=${MYHOME}/LOGS/log; export MT_LOG
MT_TMP=${MYHOME}/LOGS/tmp; export MT_TMP
TMP=${MT_TMP}; export TMP
TMPPROJECT=${MT_TMP}; export TMPPROJECT
MT_DB_LOGIN=${DBCONNECT}; export MT_DB_LOGIN

# Create required directories
mkdir -p sysfile
mkdir -p ${SPOOL}
mkdir -p ${MT_ACC_FILEPATH}
mkdir -p ${MT_LOG}
mkdir -p ${TMP}
touch ${MT_ACC_FILEPATH}/AccWait ${MT_ACC_FILEPATH}/AccLock

COB_EXTFH_LIB=$COBOLITDIR/lib/libbdbextfh.so; export COB_EXTFH_LIB
COB_EXTFH_INDEXED=BDBEXTFH; export COB_EXTFH_INDEXED

unset COB_ENABLE_XA

